import { IdeType, IdePreset } from './types';

// ─── Common ARM strip flags (clangd can't handle these GCC-specific variants) ─
const ARM_STRIP: string[] = [
  '-mcpu=*', '-mfpu=*', '-mfloat-abi=*',
  '-specs=*', '--specs=*', '-march=*',
  '-mfix-cortex-m3-ldrd',               // older GCC ARM quirk
];

// ─── PIC32 / MIPS strip flags ────────────────────────────────────────────────
const MIPS_STRIP: string[] = [
  '-mips*', '-mprocessor=*', '-mdfp=*', '-mno-*',
  '-G*', '-msda=*', '-mxgot',
  '--defsym=*',
];

export const IDE_PRESETS: Record<IdeType, IdePreset> = {

  // ── NXP S32 Design Studio (Eclipse CDT) ────────────────────────────────────
  s32ds: {
    displayName:    'NXP S32 Design Studio',
    compilerHint:   'e.g. C:/NXP/S32DS.3.5/S32DS/build_tools/arm-none-eabi-gcc-9/bin/arm-none-eabi-gcc.exe',
    buildFolders:   ['Debug_FLASH', 'Debug_RAM', 'Release_FLASH', 'Release_RAM', 'Debug', 'Release', 'build'],
    targetTriple:   'arm-none-eabi',
    cpuFlags:       ['-mcpu=cortex-m4', '-mthumb'],
    stripFlags:     ARM_STRIP,
    cStandard:      'c11',
    projectFiles:   ['.cproject', '.project'],
    fallbackParser: 'eclipse',
  },

  // ── Microchip MPLAB X IDE ───────────────────────────────────────────────────
  // MPLAB X generates Makefiles under dist/<config>/<type>/
  // and nbproject/Makefile-<config>.mk for each build config.
  // XC8 (PIC), XC16 (dsPIC/PIC24), XC32 (PIC32/SAM) are separate compilers.
  mplab: {
    displayName:    'Microchip MPLAB X IDE',
    compilerHint:   'e.g. C:/Program Files/Microchip/xc32/v4.30/bin/xc32-gcc.exe  (or xc8-cc / xc16-gcc)',
    buildFolders:   [
      'dist/default/production',
      'dist/default/debug',
      'dist/Debug/production',
      'dist/Release/production',
      'build/default',
      'build/Debug',
      'build/Release',
    ],
    targetTriple:   'mipsel-unknown-elf',      // PIC32 default; override for XC8/XC16
    cpuFlags:       [],                         // XC compilers vary widely; leave to user
    stripFlags:     [
      ...MIPS_STRIP,
      '-mprocessor=*',
      '--errformat=*', '--warnformat=*', '--msgformat=*',  // XC8 diagnostic format flags
      '-mno-float',
    ],
    cStandard:      'c99',
    projectFiles:   ['nbproject/project.xml', 'nbproject/configurations.xml'],
    fallbackParser: 'mplab',
  },

  // ── STMicroelectronics STM32CubeIDE (also Eclipse CDT based) ──────────────
  // Build output goes to Debug/ or Release/ with sub-makefiles like:
  //   Debug/Src/subdir.mk, Debug/Drivers/subdir.mk etc.
  stm32: {
    displayName:    'STM32CubeIDE',
    compilerHint:   'e.g. C:/ST/STM32CubeIDE_1.14.0/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.12.3.rel1.win32.x86_64_1.0.200.202312111845/tools/bin/arm-none-eabi-gcc.exe',
    buildFolders:   ['Debug', 'Release'],
    targetTriple:   'arm-none-eabi',
    cpuFlags:       ['-mcpu=cortex-m4', '-mthumb', '-mfpu=fpv4-sp-d16', '-mfloat-abi=hard'],
    stripFlags:     ARM_STRIP,
    cStandard:      'c11',
    projectFiles:   ['.cproject', '.project', '.mxproject'],
    fallbackParser: 'eclipse',
  },

  // ── Generic / Other ────────────────────────────────────────────────────────
  generic: {
    displayName:    'Generic / Custom',
    compilerHint:   'Full path to compiler executable',
    buildFolders:   ['Debug', 'Release', 'build', 'out'],
    targetTriple:   'arm-none-eabi',
    cpuFlags:       [],
    stripFlags:     ARM_STRIP,
    cStandard:      'c11',
    projectFiles:   [],
    fallbackParser: 'none',
  },
};

/**
 * Auto-detect which IDE produced this project by looking for marker files.
 * Returns null if nothing matches (caller should use user setting or 'generic').
 */
export function detectIde(projectRoot: string): IdeType | null {
  const fs = require('fs') as typeof import('fs');
  const path = require('path') as typeof import('path');

  // MPLAB X: always has nbproject/
  if (fs.existsSync(path.join(projectRoot, 'nbproject', 'project.xml'))) {
    return 'mplab';
  }

  // STM32CubeIDE: has .mxproject (generated by STM32CubeMX)
  if (fs.existsSync(path.join(projectRoot, '.mxproject'))) {
    return 'stm32';
  }

  // S32DS: Eclipse CDT .cproject but NOT STM32 (no .mxproject).
  // Distinguish from plain STM32CubeIDE by checking for S32DS-specific
  // superClass patterns in .cproject.
  if (fs.existsSync(path.join(projectRoot, '.cproject'))) {
    const content = fs.readFileSync(path.join(projectRoot, '.cproject'), 'utf8');
    if (content.includes('com.nxp') || content.includes('s32ds') || content.includes('freescale')) {
      return 's32ds';
    }
    // Fall through to stm32 if it looks like ST
    if (content.includes('com.st.') || content.includes('stm32')) {
      return 'stm32';
    }
    // Generic Eclipse CDT — treat as s32ds (Eclipse-based fallback parser)
    return 's32ds';
  }

  return null;
}

/**
 * Merge: IDE preset → user config overrides.
 * Any non-empty user value wins over the preset default.
 */
export function applyPreset(
  preset: IdePreset,
  userOverrides: Partial<{
    compilerPath:  string;
    makePath:      string;
    buildFolders:  string[];
    targetTriple:  string;
    cpuFlags:      string[];
    stripFlags:    string[];
    cStandard:     string;
    extraIncludes: string[];
    extraDefines:  string[];
  }>
): {
  compilerPath:  string;
  makePath:      string;
  buildFolders:  string[];
  targetTriple:  string;
  cpuFlags:      string[];
  stripFlags:    string[];
  cStandard:     string;
  extraIncludes: string[];
  extraDefines:  string[];
} {
  return {
    compilerPath:  userOverrides.compilerPath  || '',
    makePath:      userOverrides.makePath       || 'make',
    buildFolders:  (userOverrides.buildFolders && userOverrides.buildFolders.length > 0)
                     ? userOverrides.buildFolders
                     : preset.buildFolders,
    targetTriple:  userOverrides.targetTriple   || preset.targetTriple,
    cpuFlags:      (userOverrides.cpuFlags && userOverrides.cpuFlags.length > 0)
                     ? userOverrides.cpuFlags
                     : preset.cpuFlags,
    stripFlags:    (userOverrides.stripFlags && userOverrides.stripFlags.length > 0)
                     ? userOverrides.stripFlags
                     : preset.stripFlags,
    cStandard:     userOverrides.cStandard      || preset.cStandard,
    extraIncludes: userOverrides.extraIncludes  || [],
    extraDefines:  userOverrides.extraDefines   || [],
  };
}
