/**
 * codexIndex.ts
 *
 * Two artifacts the agent maintains for itself and for the reader:
 *
 * R7/R8 — `.codex/index.json`: a compact, machine-optimised projection of
 *   the whole knowledge base. One file, one read, no directory walking, no
 *   markdown parsing. This is what the agent loads to answer "which
 *   functions touch SPI?" or "what calls this?" without opening N files.
 *
 * R9 — `.codex/ARCHITECTURE.md`: the human entry point. A reader starts
 *   here and can navigate the entire system through links, never opening
 *   a .c file.
 *
 * No vscode dependency — directly unit-testable.
 */

export interface IndexedFunction {
  n: string;   // name
  f: string;   // file (relative)
  l: number;   // line
  p: string;   // purpose
  cr: string[]; // callers
  ce: string[]; // callees
  x: boolean;  // has user correction (authoritative)
}

export interface IndexedModule {
  f: string;   // file (relative)
  p: string;   // purpose
  pub: string[];  // public API function names
  dep: string[];  // extern dependencies
  x: boolean;
}

export interface IndexedFolder {
  d: string;   // folder path ('' = root)
  p: string;   // purpose
  files: string[];
  subs: string[];
  x: boolean;
}

export interface CodexIndex {
  version: number;
  generated: string;
  diagramFormat: string;
  counts: { functions: number; modules: number; folders: number };
  functions: IndexedFunction[];
  modules: IndexedModule[];
  folders: IndexedFolder[];
  /** Flat adjacency: caller -> callees, for O(1) graph walks */
  callGraph: Record<string, string[]>;
  /** Distinct vendor/extern symbols referenced anywhere */
  externs: string[];
}

export const INDEX_VERSION = 1;

export function buildIndex(input: {
  diagramFormat: string;
  functions: IndexedFunction[];
  modules: IndexedModule[];
  folders: IndexedFolder[];
  externs: string[];
}): CodexIndex {
  const callGraph: Record<string, string[]> = {};
  for (const fn of input.functions) {
    if (fn.ce.length) { callGraph[fn.n] = fn.ce; }
  }
  return {
    version: INDEX_VERSION,
    generated: new Date().toISOString(),
    diagramFormat: input.diagramFormat,
    counts: {
      functions: input.functions.length,
      modules: input.modules.length,
      folders: input.folders.length
    },
    functions: input.functions,
    modules: input.modules,
    folders: input.folders,
    callGraph,
    externs: [...new Set(input.externs)].sort()
  };
}

/** N-hop neighbourhood walk over the index's call graph — the retrieval
 *  primitive that keeps context small (ties to the Context Engine in
 *  PLAN.md Phase 1). Returns function names, including the seed. */
export function neighbourhood(index: CodexIndex, seed: string, hops: number): string[] {
  const reverse: Record<string, string[]> = {};
  for (const [caller, callees] of Object.entries(index.callGraph)) {
    for (const callee of callees) {
      (reverse[callee] ??= []).push(caller);
    }
  }
  const seen = new Set<string>([seed]);
  let frontier = [seed];
  for (let h = 0; h < hops; h++) {
    const next: string[] = [];
    for (const name of frontier) {
      for (const nbr of [...(index.callGraph[name] ?? []), ...(reverse[name] ?? [])]) {
        if (!seen.has(nbr)) { seen.add(nbr); next.push(nbr); }
      }
    }
    if (next.length === 0) { break; }
    frontier = next;
  }
  return [...seen];
}

/** Renders the human entry point. `diagramExt` is '.puml' or '.mmd'. */
export function renderArchitectureMd(index: CodexIndex, diagramExt: string): string {
  const root = index.folders.find(f => f.d === '');
  const topFolders = index.folders
    .filter(f => f.d !== '' && !f.d.includes('/'))
    .sort((a, b) => a.d.localeCompare(b.d));

  const lines: string[] = [
    '# Architecture Overview',
    '',
    '> Auto-generated by Codex Intelligence. Start here — you should be able to',
    '> understand this codebase by reading these documents alone, without opening',
    '> the source files.',
    '',
    `**Generated:** ${index.generated}  `,
    `**Diagram format:** ${index.diagramFormat}  `,
    `**Coverage:** ${index.counts.functions} functions · ${index.counts.modules} files · ${index.counts.folders} folders`,
    ''
  ];

  if (root?.p) {
    lines.push('## What this system is', '', root.p, '');
  }

  lines.push('## System behaviour', '');
  lines.push(`- [Whole-system component diagram](behaviour/system_behaviour${diagramExt})`);
  lines.push('');

  if (topFolders.length) {
    lines.push('## Top-level structure', '');
    for (const f of topFolders) {
      lines.push(`### \`${f.d}/\``);
      lines.push('');
      lines.push(f.p || '_(no overview yet)_');
      lines.push('');
      lines.push(`[Folder details →](tree/${f.d}/_folder.md)`);
      lines.push('');
    }
  }

  lines.push('## All modules', '');
  lines.push('| File | Purpose | Public API |');
  lines.push('|---|---|---|');
  for (const m of [...index.modules].sort((a, b) => a.f.localeCompare(b.f))) {
    const api = m.pub.length ? m.pub.map(n => `\`${n}\``).join(', ') : '—';
    const purpose = (m.p || '—').replace(/\|/g, '\\|');
    lines.push(`| [\`${m.f}\`](tree/${m.f}.md) | ${purpose} | ${api} |`);
  }
  lines.push('');

  if (index.externs.length) {
    lines.push('## Vendor / external boundary', '');
    lines.push('These symbols are called by this codebase but are **not** part of it —');
    lines.push('they belong to the silicon vendor SDK and were deliberately not analysed:');
    lines.push('');
    for (const e of index.externs.slice(0, 40)) { lines.push(`- \`${e}\``); }
    if (index.externs.length > 40) { lines.push(`- _…and ${index.externs.length - 40} more_`); }
    lines.push('');
  }

  lines.push('## How to navigate', '');
  lines.push('| Looking for | Go to |');
  lines.push('|---|---|');
  lines.push('| What a folder does | `tree/<path>/_folder.md` |');
  lines.push('| What a file does, and its public API | `tree/<path>/<file>.md` |');
  lines.push('| What one function does, callers and callees | `functions/<name>.md` |');
  lines.push(`| Call flow through a module | \`flows/<module>${diagramExt}\` |`);
  lines.push(`| Who calls whom, in order | \`sequences/<module>${diagramExt}\` |`);
  lines.push(`| State machine for a module | \`states/<module>${diagramExt}\` |`);
  lines.push(`| Whole-system component view | \`behaviour/system_behaviour${diagramExt}\` |`);
  lines.push('| Raw call graph (Graphviz) | `callgraph/<module>.dot` |');
  lines.push('| Machine-readable index (for tools) | `index.json` |');
  lines.push('');
  lines.push('## Correcting this documentation', '');
  lines.push('The agent reads your edits back as authoritative. Two ways to contribute:', '');
  lines.push('1. **Add notes** anywhere inside a `<!-- codex:user-start -->` / `<!-- codex:user-end -->`');
  lines.push('   block. That content is never overwritten.');
  lines.push('2. **Correct a field** by inserting `[corrected]` after its label:');
  lines.push('   ```markdown');
  lines.push('   **Purpose:** [corrected] Actually drives the motor, not the LED.');
  lines.push('   ```');
  lines.push('   The agent keeps your text and treats it as ground truth from then on.');
  lines.push('');

  return lines.join('\n');
}
