/**
 * Compilation database handling.
 *
 * The flags matter more here than anywhere else in the project. Dumping an AST
 * with host defaults for code compiled for a Cortex-M gives you an AST for a
 * program that does not exist: different `sizeof(long)`, different alignment,
 * different preprocessor branches taken. `--target`, `--sysroot` and every `-D`
 * must survive from the real build command into the dump command, or the lens
 * quietly explains the wrong program.
 *
 * So the rule is: keep everything by default, and remove only the flags that are
 * actively incompatible with `-fsyntax-only -ast-dump`. An unknown flag is kept.
 */

export interface CompileEntry {
  directory: string;
  file: string;
  command?: string;
  arguments?: string[];
  output?: string;
}

export class CompDbError extends Error {}

/**
 * Split a shell command into argv, honouring quotes and backslash escapes.
 * Compilation databases produced on Windows routinely contain quoted paths with
 * spaces, and splitting on whitespace corrupts them.
 */
export function shellSplit(command: string): string[] {
  const out: string[] = [];
  let current = '';
  let quote: '"' | "'" | undefined;
  let started = false;

  for (let i = 0; i < command.length; i++) {
    const ch = command[i];
    if (quote) {
      if (ch === '\\' && quote === '"' && i + 1 < command.length) {
        current += command[++i];
      } else if (ch === quote) {
        quote = undefined;
      } else {
        current += ch;
      }
      continue;
    }
    if (ch === '"' || ch === "'") {
      quote = ch;
      started = true;
    } else if (/\s/.test(ch)) {
      if (started || current.length > 0) {
        out.push(current);
        current = '';
        started = false;
      }
    } else if (ch === '\\' && i + 1 < command.length && /\s/.test(command[i + 1])) {
      current += command[++i];
    } else {
      current += ch;
    }
  }
  if (started || current.length > 0) {
    out.push(current);
  }
  return out;
}

export function parseCompilationDatabase(text: string): CompileEntry[] {
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch (err) {
    throw new CompDbError(`compile_commands.json is not valid JSON: ${(err as Error).message}`);
  }
  if (!Array.isArray(raw)) {
    throw new CompDbError('compile_commands.json must be a JSON array');
  }
  return raw.filter((e): e is CompileEntry => {
    const o = e as CompileEntry;
    return typeof o?.file === 'string' && typeof o?.directory === 'string';
  });
}

function normalise(p: string): string {
  return p.replace(/\\/g, '/').replace(/\/+/g, '/').toLowerCase();
}

/**
 * Find the entry for a source file. Falls back to a basename match because
 * compilation databases record paths relative to the build directory, which is
 * frequently not where the editor thinks the file is.
 */
export function entryFor(entries: CompileEntry[], filePath: string): CompileEntry | undefined {
  const want = normalise(filePath);
  const exact = entries.find((e) => normalise(e.file) === want || want.endsWith(normalise(e.file)));
  if (exact) {
    return exact;
  }
  const base = want.split('/').pop();
  return entries.find((e) => normalise(e.file).split('/').pop() === base);
}

/**
 * Remove arguments that are not arguments.
 *
 * Compilation databases generated from a `compile_flags.txt` sometimes carry the
 * file's comment lines through into `arguments`. A compiler treats those as
 * input filenames and reports "no such file or directory: '# generated by ...'",
 * which reads as a missing header rather than as a malformed database.
 *
 * Applied to every consumer, including the copy handed to clang-uml, because the
 * database is an input Lens does not control and a comment is never a flag.
 */
export function stripNonArguments(argv: string[]): string[] {
  return argv.filter((a) => {
    const t = a.trim();
    return t.length > 0 && !t.startsWith('#') && !t.startsWith('//');
  });
}

/** Flags that take a separate value argument and must be dropped as a pair. */
const DROP_WITH_VALUE = new Set(['-o', '-MF', '-MT', '-MQ', '-MD', '-MMD', '--serialize-diagnostics']);

/** Flags that are meaningless or harmful under -fsyntax-only -ast-dump. */
const DROP_EXACT = new Set(['-c', '-S', '-E', '-M', '-MM', '-MG', '-MP', '-flto', '-fno-lto', '-pipe', '-g']);

const DROP_PREFIX = ['-Wl,', '-flto=', '--param=ssp', '-fprofile', '-fdump-', '-save-temps', '-specs='];

/**
 * Sanitise a build command into flags suitable for an AST dump.
 *
 * The compiler argv[0] is dropped — Lens substitutes its own configured clang —
 * as is the source file itself, which the caller appends. Everything else that
 * is not on the drop list survives, including flags Lens does not recognise:
 * a `-mcpu` or a vendor `-D` that got silently discarded would change the AST
 * without changing anything visible.
 */
export function sanitiseFlags(argv: string[], sourceFile: string): string[] {
  argv = stripNonArguments(argv);
  const out: string[] = [];
  const wantFile = normalise(sourceFile);
  const wantBase = wantFile.split('/').pop();

  for (let i = 1; i < argv.length; i++) {
    const a = argv[i];
    if (DROP_WITH_VALUE.has(a)) {
      // -MD and -MMD take no value; the rest do.
      if (a !== '-MD' && a !== '-MMD') {
        i += 1;
      }
      continue;
    }
    if (DROP_EXACT.has(a) || DROP_PREFIX.some((p) => a.startsWith(p))) {
      continue;
    }
    // The source file appears as a bare argument; the caller re-adds it.
    if (!a.startsWith('-') && (normalise(a) === wantFile || normalise(a).split('/').pop() === wantBase)) {
      continue;
    }
    out.push(a);
  }
  return out;
}

/**
 * Ordered candidate paths for a compilation database.
 *
 * The setting accepts a *file* as well as a directory, because
 * `compile_commands.json` is not the only name in use — build systems and
 * hand-maintained projects routinely produce `compile_commands_fixed.json` or
 * one file per configuration, and a setting that only takes a directory cannot
 * express that.
 */
export function databaseCandidates(root: string, configured?: string, join = defaultJoin): string[] {
  if (configured && configured.length > 0) {
    const base = isAbsolutePath(configured) ? configured : join(root, configured);
    // A path ending in .json is the file itself; anything else is a directory.
    return configured.toLowerCase().endsWith('.json') ? [base] : [join(base, 'compile_commands.json')];
  }
  return ['.', 'build', 'out', 'Debug', 'Release', '.vscode'].map((d) =>
    d === '.' ? join(root, 'compile_commands.json') : join(root, d, 'compile_commands.json'),
  );
}

function isAbsolutePath(p: string): boolean {
  return p.startsWith('/') || /^[A-Za-z]:[\\/]/.test(p);
}

function defaultJoin(...parts: string[]): string {
  return parts.join('/').replace(/\/+/g, '/');
}

export type SourceLanguage = 'c' | 'c++';

/**
 * Which language an entry is compiled as.
 *
 * This decides the clang driver mode, and getting it wrong is fatal rather than
 * degraded: `clang++` given `-std=c11` refuses to run at all. The `-x` flag wins
 * if present, then an explicit `-std=`, then the file extension — which is the
 * order the compiler itself resolves them in.
 */
export function languageOf(entry: CompileEntry): SourceLanguage {
  const argv = entry.arguments ?? shellSplit(entry.command ?? '');
  const xIndex = argv.indexOf('-x');
  if (xIndex >= 0 && argv[xIndex + 1]) {
    return argv[xIndex + 1].startsWith('c++') ? 'c++' : 'c';
  }
  const std = argv.find((a) => a.startsWith('-std='));
  if (std) {
    return /^-std=(c|gnu)\d/.test(std) ? 'c' : 'c++';
  }
  return /\.(cpp|cc|cxx|c\+\+|C|hpp|hh|hxx)$/.test(entry.file) ? 'c++' : 'c';
}

export interface AstCommand {
  /** Working directory the flags are relative to. */
  cwd: string;
  args: string[];
  language: SourceLanguage;
}

/**
 * Build the argv for dumping one declaration's AST.
 *
 * `-ast-dump-filter` is what makes this viable at all: unfiltered, a real
 * translation unit dumps hundreds of megabytes of header declarations.
 */
/**
 * Flags the user adds by hand, injected into every command Lens builds.
 *
 * The escape hatch for a compilation database that is missing something its
 * project needs — most often the vendor device macro, without which every CMSIS
 * header fails. Placed after the compiler and before the project's own flags so
 * a project can still override them.
 */
export let extraCompileFlags: string[] = [];

export function setExtraCompileFlags(flags: string[]): void {
  extraCompileFlags = flags.filter((f) => f.trim().length > 0);
}

function driverArgs(entry: CompileEntry): { language: SourceLanguage; args: string[] } {
  const language = languageOf(entry);
  // The configured binary is usually clang++, and clang++ given a C standard
  // refuses to run rather than adapting. --driver-mode makes one binary serve
  // both languages, so the user does not have to configure two paths.
  return {
    language,
    args: [`--driver-mode=${language === 'c' ? 'gcc' : 'g++'}`, ...extraCompileFlags],
  };
}

export function buildAstCommand(entry: CompileEntry, declName: string): AstCommand {
  const argv = entry.arguments ?? shellSplit(entry.command ?? '');
  if (argv.length === 0) {
    throw new CompDbError(`compilation database entry for ${entry.file} has neither "command" nor "arguments"`);
  }
  const driver = driverArgs(entry);
  return {
    cwd: entry.directory,
    language: driver.language,
    args: [
      ...driver.args,
      ...sanitiseFlags(argv, entry.file),
      '-fsyntax-only',
      '-Xclang',
      '-ast-dump=json',
      '-Xclang',
      `-ast-dump-filter=${declName}`,
      entry.file,
    ],
  };
}

/** The same flags, dumping record layouts instead of an AST. */
export function buildRecordLayoutCommand(entry: CompileEntry): AstCommand {
  const argv = entry.arguments ?? shellSplit(entry.command ?? '');
  if (argv.length === 0) {
    throw new CompDbError(`compilation database entry for ${entry.file} has neither "command" nor "arguments"`);
  }
  const driver = driverArgs(entry);
  return {
    cwd: entry.directory,
    language: driver.language,
    args: [
      ...driver.args,
      ...sanitiseFlags(argv, entry.file),
      '-fsyntax-only',
      '-Xclang',
      '-fdump-record-layouts',
      entry.file,
    ],
  };
}
